name: Build PHP

on:
  push:
    
  release:
    types: [published]

jobs:
  build-and-publish:
    permissions:
      contents: write
      packages: write      
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  


    - name: Build
      run: bash build-php.sh

    - name: Upload PHP artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-php
        path: build/php

    - name: Prepare asset for upload
      run: |
        tar -czf build/openagents_grpc_proto-PHP.tar.gz -C build/php/ .
       
    - name: Upload release asset
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: build/openagents_grpc_proto-PHP.tar.gz
        