name: Build PHP

on:
  push:
    
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write      

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'  

    - name: Install Protocol Buffers compiler
      run: sudo apt-get install -y protobuf-compiler

    - name: Build
      run: bash build-php.sh   

    - name: Upload PHP artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-php
        path: build/php