name: Build PHP

on:
  push:
    
  release:
    types: [published]

jobs:
  build-and-publish:
    permissions:
      contents: write
      packages: write      
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  


    - name: Build
      run: echo TODO

    # - name: Upload PHP artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: build-php
    #     path: build/php