name: Build Python

on:
  push:
    
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write      

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  

    - name: Build
      run: bash build-python.sh

    - name: Upload Python artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-python
        path: build/python/openagents_service_provider_proto
    
    - name: Upload Python dist
      uses: actions/upload-artifact@v2
      with:
        name: dist-python
        path: build/python/dist
    
    - name: Upload release asset
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: build/python/dist/*.tar.gz